### ISSUE TITLE
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False

### ISSUE THREAD

**Issue by muzaluisa** [aalto-speech/ner-asr#1]
Hey,

Apparently while loading the model in evaluate_document.py there is a mistake
_RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False_

You can update the script this way to make it work for those loading the model with CPU :)

```
# load the model
    if lowercase_model == False:
        model.load_state_dict(torch.load('weights/model_upper.pt', map_location=torch.device('cpu')))
    else:
        model.load_state_dict(torch.load('weights/model_lower.pt', map_location=torch.device('cpu')))
```

**Comment by Tetrix** [comment]
Hi,

Thank you very much for the feedback.
I updated the script, so now the issue should be gone.
Also changed the loading of the embeddings, now it is done using the fasttext library, which is significantly faster

**Comment by muzaluisa** [comment]
Many thanks, and great that you made loading faster, it is smth that I was wondering as well!
